app:
  version: '@project.version@'

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/my_app_db?useSSL=false&serverTimezone=UTC
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{X-Correlation-Id}] [%X{User-Id}] %-5level %logger - %msg%n"
